package dev.spring.ai.controller;

import dev.spring.ai.service.MeetingService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/meeting")
public class MeetingController
{
	/** Service handling meeting-related operations. */
	private final MeetingService promptService;

	/**
	 * Constructs a MeetingController with the required MeetingService.
	 *
	 * @param promptService the service used to handle meeting questions; injected by Spring
	 */
	public MeetingController(MeetingService promptService)
	{
	    // assign injected service to the controller field
	    this.promptService = promptService;
	}


	/**
	 * Endpoint to ask a meeting-related question.
	 *
	 * Example request: GET /meeting?question=What%20is%20the%20agenda
	 *
	 * @param question the question to ask the MeetingService; required
	 * @return response generated by {@code MeetingService#askQuestion(String)}
	 */
	@GetMapping
	public String askQuestion(@RequestParam(name = "question", required = true) String question)
	{
	    // Delegate the question to the service and return its answer.
	    return promptService.askQuestion(question);
	}
}
