spring.application.name=ai
server.servlet.context-path=/spring-ai
spring.ai.openai.api-key=${SECRET}
spring.ai.openai.chat.options.model=gpt-4.1-nano
spring.ai.retry.max-attempts=1
spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=1536


spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.environment=us-east-1-aws
spring.ai.vectorstore.pinecone.index-name=${PINECONE_Index}
spring.ai.vectorstore.pinecone.namespace=default